---

# Setup NGINX Repository

- name: building and installing NGINX from source and compiled with mod_pagespeed
  run_once: true
  shell: sudo bash <(curl -f -L -sS https://ngxpagespeed.com/install) --nginx-version latest -a '--prefix=/usr/share/nginx --sbin-path=/usr/sbin/nginx --modules-path=/usr/lib/nginx/modules --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --pid-path=/run/nginx.pid --lock-path=/var/lock/nginx.lock --user=www-data --group=www-data --build=Ubuntu --with-compat --with-file-aio --with-threads --with-http_addition_module --with-http_auth_request_module --with-http_dav_module --with-http_flv_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_mp4_module --with-http_random_index_module --with-http_realip_module --with-http_secure_link_module --with-http_slice_module --with-http_ssl_module --with-http_stub_status_module --with-http_sub_module --with-http_v2_module --with-mail --with-mail_ssl_module --with-stream --with-stream_realip_module --with-stream_ssl_module --with-stream_ssl_preread_module ' --assume-yes
#--with-cc-opt="-g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fPIC" --with-ld-opt="-Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -pie"

#- name: Transfer NGINX script
#  copy: src=templates/nginx-source.sh dest=/etc mode=0777

#- name: Execute NGINX script
#  local_action: command sudo sh /etc/nginx-source.sh
  
- name: add nginx init script for NGINX
  run_once: true
  template: src=templates/nginx.service dest=/etc/systemd/system/

- name: Start and enable NGINX service
  run_once: true
  shell: sudo systemctl start nginx.service && sudo systemctl enable nginx.service

- name: Ensure /etc/nginx directories exist
  run_once: true
  file: path={{ item }} state=directory owner=root group=root mode=0755
  with_items:
    - /etc/nginx/sites-available
    - /etc/nginx/sites-enabled
    - /etc/nginx/global 
    - /etc/nginx/server
    - /var/cache/nginx 

#remove default files
- name: Remove default conf.d
  run_once: true
  file: path=/etc/nginx/conf.d/default.conf state=absent

- name: Remove example ssl conf.d
  run_once: true
  file: path=/etc/nginx/conf.d/example_ssl.conf state=absent

- name: Remove example ssl conf.d
  run_once: true
  file: path=/etc/nginx/conf.d/ssl.conf state=absent  

- name: Remove gent.conf
  run_once: true
  file: path=/etc/nginx/conf.d/agent.conf state=absent 

- name: Remove cache-file-descriptors.conf
  run_once: true
  file: path=/etc/nginx/conf.d/cache-file-descriptors.conf state=absent

- name: Remove gzip.conf
  run_once: true
  file: path=/etc/nginx/conf.d/gzip.conf state=absent

- name: Remove header.conf
  run_once: true
  file: path=/etc/nginx/conf.d/header.conf state=absent

- name: Remove real_ip.conf
  run_once: true
  file: path=/etc/nginx/conf.d/real_ip.conf state=absent

- name: Remove log.conf
  run_once: true
  file: path=/etc/nginx/conf.d/log.conf state=absent

- name: Remove fastcgi.conf
  run_once: true
  file: path=/etc/nginx/conf.d/fastcgi.conf state=absent

- name: Remove blockip.conf
  run_once: true
  file: path=/etc/nginx/conf.d/blockip.conf state=absent

- name: Remove limit_request.conf
  run_once: true
  file: path=/etc/nginx/conf.d/limit_request.conf state=absent
        
# Setup NGINX pagespeed

- name: "Set server pagespeed"
  template: src=server/pagespeed.conf dest=/etc/nginx/server/

- name: "Set global pagespeed"
  template: src=global/pagespeed.conf dest=/etc/nginx/global/

## rest of the nginx configuration work


- name: "Set up fastcgi-params"
  template: src=global/gzip.conf dest=/etc/nginx/global/

- name: "Set up gzip"
  template: src=global/fastcgi-params.conf dest=/etc/nginx/global/

- name: "Set up http"
  template: src=global/http.conf dest=/etc/nginx/global/

- name: "Set up limits"
  template: src=global/limits.conf dest=/etc/nginx/global/

- name: "Set up mime-type"
  template: src=global/mime-types.conf dest=/etc/nginx/global/

- name: "Set up exclusions"
  template: src=server/exclusions.conf dest=/etc/nginx/server/

- name: "Set up fastcgi"
  template: src=server/fastcgi-cache.conf dest=/etc/nginx/server/

- name: "Set up security"
  template: src=server/security.conf dest=/etc/nginx/server/

- name: "Set up ssl"
  template: src=server/ssl.conf dest=/etc/nginx/server/

- name: "Set up static file"
  template: src=server/static-files.conf dest=/etc/nginx/server/

- name: Configure /etc/nginx/nginx.conf
  template: src=nginx.conf dest=/etc/nginx/nginx.conf owner=root group=root mode=0644
  notify: nginx restart


- name: Disable default server
  file:
    path: "{{ nginx_path }}/sites-enabled/default"
    state: absent
  notify: reload nginx


- name: Ensure main docroot exists
  run_once: true
  file: path={{ www_root }} state=directory

- name: Set up master docroot
  run_once: true
  file: path={{ www_root }} state=directory owner={{ web_user }} group={{ web_group }} mode=0775

- name: Make sure Nginx is running
  run_once: true
  service: name=nginx state=started enabled=yes
