---

# Setup NGINX Repository

- name: Adding NGINX Repository Key, Hold on...
  apt_key:
    id: B9C9F7DE
    url: http://download.opensuse.org/repositories/home:AnsiPress/xUbuntu_16.04/Release.key
  register: apt_key
  when: ansible_distribution == 'Ubuntu'

- name: Adding NGINX Repository, Hold on...
  apt_repository: repo='deb http://download.opensuse.org/repositories/home:/AnsiPress/xUbuntu_16.04/ /' state=present filename=nginx
  register: repository
  when: ansible_distribution == 'Ubuntu'

# Execute apt-get update
- name: Executing apt-get update command, Hold on...
  apt: update_cache=yes
  when: repository.changed == True or apt_key.changed == True


- name: Remove default conf.d
  run_once: true
  file: path=/etc/nginx/conf.d/default.conf state=absent

- name: Remove example ssl conf.d
  run_once: true
  file: path=/etc/nginx/conf.d/example_ssl.conf state=absent

- name: Remove example ssl conf.d
  run_once: true
  file: path=/etc/nginx/conf.d/ssl.conf state=absent  

- name: Remove gent.conf
  run_once: true
  file: path=/etc/nginx/conf.d/agent.conf state=absent 

- name: Remove cache-file-descriptors.conf
  run_once: true
  file: path=/etc/nginx/conf.d/cache-file-descriptors.conf state=absent

- name: Remove gzip.conf
  run_once: true
  file: path=/etc/nginx/conf.d/gzip.conf state=absent

- name: Remove header.conf
  run_once: true
  file: path=/etc/nginx/conf.d/header.conf state=absent

- name: Remove real_ip.conf
  run_once: true
  file: path=/etc/nginx/conf.d/real_ip.conf state=absent

- name: Remove log.conf
  run_once: true
  file: path=/etc/nginx/conf.d/log.conf state=absent

- name: Remove fastcgi.conf
  run_once: true
  file: path=/etc/nginx/conf.d/fastcgi.conf state=absent

- name: Remove blockip.conf
  run_once: true
  file: path=/etc/nginx/conf.d/blockip.conf state=absent

- name: Remove limit_request.conf
  run_once: true
  file: path=/etc/nginx/conf.d/limit_request.conf state=absent
        
# Setup NGINX pagespeed

- name: Installing NGINX, Hold on...
  apt: name=nginx-pagespeed state=present
  register: package_install
  # The notify will call the ../handlers/main.yml
  notify: service nginx restart

- name: "Set up NGINX conf.d pagespeed"
  template: src=pagespeed.conf dest=/etc/nginx/conf.d/

- name: "Set server pagespeed"
  template: src=global/server/pagespeed.conf dest=/etc/nginx/global/server/

## rest of the nginx configuration work


- name: "Set up fastcgi-params"
  template: src=global/gzip.conf dest=/etc/nginx/global/

- name: "Set up gzip"
  template: src=global/fastcgi-params.conf dest=/etc/nginx/global/

- name: "Set up http"
  template: src=global/http.conf dest=/etc/nginx/global/

- name: "Set up limits"
  template: src=global/limits.conf dest=/etc/nginx/global/

- name: "Set up mime-type"
  template: src=global/mime-types.conf dest=/etc/nginx/global/

- name: "Set up exclusions"
  template: src=global/server/exclusions.conf dest=/etc/nginx/global/server/

- name: "Set up fastcgi"
  template: src=global/server/fastcgi-cache.conf dest=/etc/nginx/global/server/

- name: "Set up security"
  template: src=global/server/security.conf dest=/etc/nginx/global/server/

- name: "Set up ssl"
  template: src=global/server/ssl.conf dest=/etc/nginx/global/server/

- name: "Set up static file"
  template: src=global/server/static-files.conf dest=/etc/nginx/global/server/

- name: Configure /etc/nginx/nginx.conf
  template: src=nginx.conf dest=/etc/nginx/nginx.conf owner=root group=root mode=0644
  notify: nginx restart


- name: Disable default server
  file:
    path: "{{ nginx_path }}/sites-enabled/default"
    state: absent
  notify: reload nginx


- name: Ensure main docroot exists
  run_once: true
  file: path={{ www_root }} state=directory

- name: Set up master docroot
  run_once: true
  file: path={{ www_root }} state=directory owner={{ web_user }} group={{ web_group }} mode=0775

- name: Make sure Nginx is running
  run_once: true
  service: name=nginx state=started enabled=yes
