---
#- name: Add PHP repo
#  apt_repository:
#    repo: ppa:ondrej/php

- name: Install PHP 7.0
  apt:
    name: "{{ item }}"
    state: present
    force: yes
  with_items:
  - php
  - php-cli
  - php-common
  - php-curl
  - php-dev
  - php-fpm
  - php-gd
  - php-mbstring
  - php-mcrypt
  - php-mysql
  - php-opcache
  - php-xml
  - php-xmlrpc
  - php-zip

- name: Install Xdebug
  apt:
    name: php-xdebug
    state: latest
  when: xdebug_install | default(false)

- name: xdebug configuration file
  template:
    src: xdebug.ini.j2
    dest: /etc/php/7.0/mods-available/xdebug.ini
  when: xdebug_install | default(false)

- name: Start php7.0-fpm service
  service:
    name: php7.0-fpm
    state: started
    enabled: true

- name: Create socket directory
  file:
    path: /var/run/php7.0-fpm/
    state: directory

- name: Disable default pool
  command: mv /etc/php/7.0/fpm/pool.d/www.conf /etc/php/7.0/fpm/pool.d/www.disabled
  args:
    creates: /etc/php/7.0/fpm/pool.d/www.disabled
  when: disable_default_pool
  notify: reload php-fpm

- name: PHP configuration file
  template:
    src: php.ini.j2
    dest: /etc/php/7.0/fpm/php.ini
  notify: reload php-fpm
