---
- name: "Add repository for PHP 7.2."
  apt_repository: 
    repo="ppa:ondrej/php" 
    update_cache=yes
#- name: Add php 7.2 PPA
#  apt_repository:
#    repo: "ppa:ondrej/php"
#    update_cache: yes

- name: Install PHP 7.2
  run_once: true
  apt:
    name: "{{ item }}"
    state: present
    force: yes
  with_items:
  - php 7.1-cli
  - php 7.1-common
  - php 7.1-curl
  - php 7.1-dev
  - php 7.1-fpm
  - php 7.1-gd
  - php 7.1-memcached
  - php 7.1-mbstring
  - php 7.1-mcrypt
  - php 7.1-mysql
  - php 7.1-opcache
  - php 7.1-xml
  - php 7.1-xmlrpc
  - php 7.1-zip
  - php 7.1-json
  - php 7.1-ldap
  - php 7.1-tidy
  - php 7.1-recode


 # php7.1-json    php7.1-ldap php7.1-tidy php7.1-recode

#- name: Install Xdebug
#  apt:
#    name: php-xdebug
#    state: latest
#  when: xdebug_install | default(false)

#- name: xdebug configuration file
#  template:
#    src: xdebug.ini.j2
#    dest: /etc/php/7.0/mods-available/xdebug.ini
#  when: xdebug_install | default(false)

- name: Start php 7.1-fpm service
  service:
    name: php 7.1-fpm
    state: started
    enabled: true

- name: Create socket directory
  file:
    path: /var/run/php 7.1-fpm/
    state: directory

#- name: Disable default pool
#  command: mv /etc/php/7.0/fpm/pool.d/www.conf /etc/php/7.0/fpm/pool.d/www.disabled
#  args:
#    creates: /etc/php/7.0/fpm/pool.d/www.disabled
#  when: disable_default_pool
#  notify: reload php-fpm

- name: PHP configuration file
  template:
    src: php.ini.j2
    dest: /etc/php/7.0/fpm/php.ini
  notify: reload php-fpm
